# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.FileField(default=0, upload_to=b'usuarios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medalha',
            name='icone',
            field=models.FileField(upload_to=b'medalhas'),
        ),
    ]
