# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_usuario_system_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='primeiro_acesso',
            field=models.BooleanField(default=False),
        ),
    ]
